/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifg.siseducar.frame;

import br.edu.ifg.poo.Main;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gilberto
 */
public class CadastroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeCadUsuario = new javax.swing.JLabel();
        jTextFieldNomeCadUsuario = new javax.swing.JTextField();
        jTextFieldLoginCadUsuario = new javax.swing.JTextField();
        jLabelLoginCadUsuario = new javax.swing.JLabel();
        jLabelSenhaCadUsuario = new javax.swing.JLabel();
        jPasswordFieldCadUsuario = new javax.swing.JPasswordField();
        jLabelConfSenhaCadUsuario = new javax.swing.JLabel();
        jPasswordFieldConfCadUsuario = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Usuário");
        setToolTipText("");

        jLabelNomeCadUsuario.setText("Nome:");

        jLabelLoginCadUsuario.setText("Login:");

        jLabelSenhaCadUsuario.setText("Senha:");

        jLabelConfSenhaCadUsuario.setText("Confirmar Senha:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNomeCadUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeCadUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLoginCadUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLoginCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSenhaCadUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldCadUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConfSenhaCadUsuario)
                            .addComponent(jButtonSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLimpar))
                            .addComponent(jPasswordFieldConfCadUsuario))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCadUsuario)
                    .addComponent(jTextFieldNomeCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginCadUsuario)
                    .addComponent(jTextFieldLoginCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenhaCadUsuario)
                    .addComponent(jPasswordFieldCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfSenhaCadUsuario)
                    .addComponent(jPasswordFieldConfCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        String nome = jTextFieldNomeCadUsuario.getText();
        String login = jTextFieldLoginCadUsuario.getText();
        String senha = jPasswordFieldCadUsuario.getText();
        String confSenha = jPasswordFieldConfCadUsuario.getText();
        
        if ("".equals(nome.trim())) {
            JOptionPane.showMessageDialog(rootPane, "Por favor informe um nome!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeCadUsuario.requestFocus();
            return;
        }
        
        if ("".equals(login.trim())) {
            JOptionPane.showMessageDialog(rootPane, "Por favor informe um usuario!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            jTextFieldLoginCadUsuario.requestFocus();
            return;
        }
        
        if ("".equals(senha.trim())) {
            JOptionPane.showMessageDialog(rootPane, "Por favor informe uma senha!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            jPasswordFieldCadUsuario.requestFocus();
            return;
        }
        
        if(!senha.equals(confSenha)){
            JOptionPane.showMessageDialog(rootPane, "Senhas diferentes, favor confirmar a senha!", "Aviso!", JOptionPane.WARNING_MESSAGE);
            jPasswordFieldCadUsuario.setText("");
            jPasswordFieldConfCadUsuario.setText("");
            jPasswordFieldCadUsuario.requestFocus();
            return;
        }
        
        //Sql para inserir os valores recebidos
        String sql = "INSERT INTO usuario VALUES ("
                + "DEFAULT, "
                + "'" + nome.toLowerCase() + "', "
                + "'" + login.toLowerCase() + "', "
                + "'" + senha + "');";
        System.out.println(sql);
        try {
            Statement stm = Main.conexao.createStatement();
            stm.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }        

        limparCampos();
        JOptionPane.showMessageDialog(rootPane, nome + " adicionado com sucesso!");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void limparCampos(){
        jTextFieldNomeCadUsuario.setText("");
        jTextFieldLoginCadUsuario.setText("");
        jPasswordFieldCadUsuario.setText("");
        jPasswordFieldConfCadUsuario.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelConfSenhaCadUsuario;
    private javax.swing.JLabel jLabelLoginCadUsuario;
    private javax.swing.JLabel jLabelNomeCadUsuario;
    private javax.swing.JLabel jLabelSenhaCadUsuario;
    private javax.swing.JPasswordField jPasswordFieldCadUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfCadUsuario;
    private javax.swing.JTextField jTextFieldLoginCadUsuario;
    private javax.swing.JTextField jTextFieldNomeCadUsuario;
    // End of variables declaration//GEN-END:variables
}
